### ISSUE TITLE
Mafiasi nickname is not displayed in Bitpoll, instead first name is displayed

### ISSUE THREAD

**Issue by Xevandylreth** [fsinfuhh/Bitpoll#104]
This is a problem for me since I have changed my first name and do not want it to be displayed next to my votes. Everywhere else on Mafiasi the chosen nickname is displayed instead of the first name, except on Bitpoll. I would greatly appreciate a fix for this.

**Comment by timonegk** [comment]
Hi, thanks for opening the issue! The nickname is now shown in the BitPoll, too. It might be necessary to log out and in again for the changes to take effect.
If you spot any other occurences of the wrong name, feel free to comment or contact us!
