### ISSUE TITLE
Randomize address URL not working after copying

### ISSUE THREAD

**Issue by joobei** [fsinfuhh/Bitpoll#14]
After copying a poll the URL spot is blank and the randomize button doesn't seem to do anything.

<img width="400" alt="screen shot 2017-11-09 at 10 53 05" src="https://user-images.githubusercontent.com/2638631/32599361-953776e0-c53c-11e7-9173-96fef5464079.png">

**Comment by Akasch** [comment]
this is fixed with the last commit
