### ISSUE TITLE
Apache WSGI problem

### ISSUE THREAD

**Issue by LudwigPommerenke** [fsinfuhh/Bitpoll#16]
Hello,
we have some problems with the Apache WSGI module. The ./manage.py runserver command runs without any issues. But if we configure Apache to serve the project, we get a 500 server error and the error.log shows the following if we try to access the page:

[Tue Nov 21 11:59:36.362213 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859] mod_wsgi (pid=3920): Target WSGI script '/opt/Bitpoll/bitpoll/wsgi.py' cannot be loaded as Python module.
[Tue Nov 21 11:59:36.362278 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859] mod_wsgi (pid=3920): Exception occurred processing WSGI script '/opt/Bitpoll/bitpoll/wsgi.py'.
[Tue Nov 21 11:59:36.363007 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859] Traceback (most recent call last):
[Tue Nov 21 11:59:36.363055 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/bitpoll/wsgi.py", line 22, in <module>
[Tue Nov 21 11:59:36.363059 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     application = Sentry(get_wsgi_application())
[Tue Nov 21 11:59:36.363065 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/.pyenv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Tue Nov 21 11:59:36.363068 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     django.setup(set_prefix=False)
[Tue Nov 21 11:59:36.363072 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/.pyenv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
[Tue Nov 21 11:59:36.363075 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Tue Nov 21 11:59:36.363080 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/.pyenv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
[Tue Nov 21 11:59:36.363083 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     self._setup(name)
[Tue Nov 21 11:59:36.363096 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/.pyenv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
[Tue Nov 21 11:59:36.363099 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     self._wrapped = Settings(settings_module)
[Tue Nov 21 11:59:36.363104 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/.pyenv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
[Tue Nov 21 11:59:36.363106 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Tue Nov 21 11:59:36.363113 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "/opt/Bitpoll/.pyenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
[Tue Nov 21 11:59:36.363115 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]     return _bootstrap._gcd_import(name[level:], package, level)
[Tue Nov 21 11:59:36.363120 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Tue Nov 21 11:59:36.363125 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Tue Nov 21 11:59:36.363130 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
[Tue Nov 21 11:59:36.363134 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
[Tue Nov 21 11:59:36.363139 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
[Tue Nov 21 11:59:36.363144 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
[Tue Nov 21 11:59:36.363148 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859]   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
[Tue Nov 21 11:59:36.363164 2017] [wsgi:error] [pid 3920:tid 140031723976448] [remote 10.172.100.97:39859] ImportError: No module named 'bitpoll'

We use a Python 3.5 virtual environment on a Ubuntu 16.04 LTS x64 server. There is no information about that issue neither in your project documentation nor the official Django documentation. Who can help here?

Our Apache host configuration is the following:

<VirtualHost *:80>
WSGIDaemonProcess bitpoll python-home=/opt/Bitpoll/.pyenv python-path=/opt/Bitpoll/bitpoll
WSGIProcessGroup bitpoll
WSGIScriptAlias / /opt/Bitpoll/bitpoll/wsgi.py process-group=bitpoll
Alias /static/ /opt/Bitpoll/_static/
<Directory /opt/Bitpoll>
Require all granted
</Directory>
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

Greetings,
Ludwig

**Comment by Akasch** [comment]
I think your python-path is not configured correctly. From the error output I think it should be python-path=/opt/Bitpoll as it tries to load bitpoll.settings (This is untested from my side as we do not use Apache)

**Comment by LudwigPommerenke** [comment]
Hello Akasch, thank you so much for the answer. I edited my config for the virtual host and all is working right now. I close this issue.
