### ISSUE TITLE
Bitpoll Admin Accounts

### ISSUE THREAD

**Issue by SirFlow4344** [fsinfuhh/Bitpoll#177]
Hi,

was unterscheidet einen bitpoll Admin Account von einem normalen User? Gibt es da gewisse Sonderrechte? Und wie erkennt man, ob ein Account ein Admin ist? Leider konnte ich da nichts zu finden. Entweder wird also meine Gruppe nicht richtig ausgelesen (was eigentlich nicht sein kann, da ich eine Umfrage der Admingruppe zuweisen kann) oder es gibt keinen Benefit Admin zu sein. 

Ein bissche Kontext: Ich nutzer bitpoll in nem docker Container und habe via OpenID einen Keycloak angebunden. 

Vielen Dank im Vorraus für die Rückmeldung!

**Comment by ftsell** [comment]
Ein admin Account hat keine von uns implementierte besondere Behandlung.

Admin ist ein Konzept, dass von [django](https://www.djangoproject.com/) geerbt wird und bringt hauptsächlich das Recht, auf `/admin` zuzugreifen ([django admin site doc](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#)). Dort können alle in der Datenbank gespeicherten Daten der App eingesehen und auch geändert werden.
