### ISSUE TITLE
The "Zurück" button in the "create choice" view is broken

### ISSUE THREAD

**Issue by GeneralGeki** [fsinfuhh/Bitpoll#18]
From the view on that is shown in the screenshot I cannot use the "Zurück" button :(

Also: First Bug I have encountered in years of use, thank you and greetings from @d120de :)

![bitpoll_bug](https://user-images.githubusercontent.com/10200056/33406248-380403cc-d56c-11e7-8ecb-0f15f18c60e0.png)

**Comment by GeneralGeki** [comment]
I should add that I was editing the poll after I created it and already posted a vote

**Comment by Akasch** [comment]
Thanks for the report, this was a issue with CSP.
I will deploy it later today
