### ISSUE TITLE
Changing the due date is not possible when using an english browser

### ISSUE THREAD

**Issue by Miterion** [fsinfuhh/Bitpoll#2]
When using an english browser the date/time field changes the date on defocusing to an invalid format, for example 06.08.2017 21:00 instead of 05.08.2017 21:00.

UPDATE
I think setting the correct locale in the date/timepicker module should fix that:
`jQuery.datetimepicker.setLocale('de');`
Source: http://xdsoft.net/jqplugins/datetimepicker/#i18n

**Comment by Akasch** [comment]
Th problem with the setLocale is that it also sets the text Localization for the widget. I think we have to either accept both formats in the backend or create custom locales in the datetimepicker
