### ISSUE TITLE
Server error at Password reset

### ISSUE THREAD

**Issue by LudwigPommerenke** [fsinfuhh/Bitpoll#21]
Hello,
we have an issue if we try to reset a password with the "Reset password" button. After clicking, we get a 500 server error. I recorded the webserver's error.log and it seems to be a problem with raven, but the pip package "raven" is installed as listed in requirements-production.txt (raven==6.3.0). It is possible to register new users and receive the registration mail, so our e-mail settings in general are set correctly. We use an Ubuntu 16.04 LTS with Apache as server and a python 3.5 virtualenv for Bitpoll. There is also a problem with encoding in the locale/de_DE/LC_MESSAGES/django.po at line 1971 because the "Ü" at "Passwort zurücksetzen" is not displayed correctly. I try to add this to the repository later. Please tell me if you need further information. Any ideas? Thanks in advance.
Greetings, Ludwig
[error.log](https://github.com/fsinfuhh/Bitpoll/files/1639534/error.log)

**Comment by Akasch** [comment]
The raven error is then rendering the 500 Page as you do not have use raven/sentry, I will look why it try to load it there.

The real problem ist: 
    django.template.exceptions.TemplateSyntaxError: The settings Variable MAIL_GREETING_DE is not     allowed to be acessed
meaning MAIL_GREETING_DE is not the settings TEMPLATE_ALLOWABLE_SETTINGS_VALUES list, I will look why it is not there in the sample

**Comment by Akasch** [comment]
the password reset issue should be fixed with e84de78 the errorpage issue will need some consideration from my side
