### ISSUE TITLE
Currently not buildable

### ISSUE THREAD

**Issue by JayDee2202** [fsinfuhh/Bitpoll#23]
Hello,
after I had to rebuild my container images I'm unable to build the production requirements:

`Could not find a version that satisfies the requirement django-markdown-app==0.11.1 (from -r requirements-production.txt (line 8)) (from versions: 0.8.5, 0.8.5.1, 0.9.3.1, 0.9.4, 0.9.4.1)
No matching distribution found for django-markdown-app==0.11.1 (from -r requirements-production.txt (line 8))
`

Both of the requirement files are listing the same version so I can't build dudle with that version provided.

**Comment by Akasch** [comment]
The django-markdown-app had some dropped versions. I have updated the dependencies and updated to Django 2.0 in the process. It should build again.
