### ISSUE TITLE
Back button while creating Poll doesn't work

### ISSUE THREAD

**Issue by Top-Ranger** [fsinfuhh/Bitpoll#24]
Hi,

the back button on creating polls does not work. 'Seems to be a content security policy' problem.

Browser: Firefox on Linux (persists on safe mode)
Error in console (from bitpoll.mafiasi.de): Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://bitpoll.mafiasi.de https://sentry.mafiasi.de 'nonce-XXXXXXXX'").

**Comment by Akasch** [comment]
After my testing it is working again. If not just comment.
