### ISSUE TITLE
Add compiled coffeescript & sass files to repo

### ISSUE THREAD

**Issue by azrdev** [fsinfuhh/Bitpoll#3]
I suggest to add the output of the `coffee` and `sass` compilers to the repository, so people using the software don't need them as dependency (installing both for the current user if no superuser privileges are available can be quite a hassle, like on a uberspace account).

**Comment by dario23** [comment]
kind of depending on the outcome of this (where i personally lean more towards "keep the original sources in git, not the products"), but if you don't add the compiled stuff to the repo, you might want to add `_static` to `.gitignore` :-)

**Comment by Akasch** [comment]
I have begun work to replace static_compiler with django-pipline on the feature_django-pipline branch (36b410cbd3741f8b966390695329b79810b3b88f is the beginning of the work). It already gets rid of the dependency to `sass`, and we are planing on convert the `coffee` scripts to plain Javascript. The django-pipline have already spotted some missing files from the used jquerry-ui framework I have to fix before it is ready.

django-pipline supports the compression/uglifiying for Javascript/CSS but this requires an external compressor, I think I let it in default off and make it easy configurable if one is installed to use it.

**Comment by Akasch** [comment]
The coffeescript is no longer needed and sass is now compiled by a python lib. So I think the compiled assets are no longer needed.
