### ISSUE TITLE
Need multi-day event with multiple timeslots (aka symposium)...

### ISSUE THREAD

**Issue by normanhendrich** [fsinfuhh/Bitpoll#43]
Hi there,

I just tried bitpoll to plan the talks/discussions for our upcoming "Symposium on crossmodal learning", which runs for three days. We have email feedback from several people listing times they can and cannot attend. Bitpoll/Doodle would be a good option to plan this (and to allow other people to directly add their timeslots instead of sending emails). 

But. Neither bitpoll (nor doodle) seem to support this. We can either have multiple timeslots on a single day, or multiple "whole" days without times. Why is that? Is this an inherent limitation of the underlying code, or just concentrating on the two most important use-cases?

Anyway, the bitpoll GUI promises that time information can be added after selecting the days, but pressing "next" finishes the poll with days-only.

**Comment by Akasch** [comment]
This was caused by a misunderstanding and a translation error. The correct mode for this use case is a "Datetime" poll
