### ISSUE TITLE
Error when creating new user without first name

### ISSUE THREAD

**Issue by Chessmasterrr** [fsinfuhh/Bitpoll#58]
When creating a new user without first and last name, a link is sent to the user by e-mail. Thereupon he can choose a password, but this always leads to the following error: 
"Sorry, but the provided token is invalid."

Creating a user with first and last name works without problems.

Expected behavior: When creating a user, the system already informs the user that he or she must enter first and last name.

The database used is sqlite.

**Comment by Akasch** [comment]
Thanks for the report, the fix is in #59 . I had forgotten about this, the code was already uncommitted on my laptop...
