### ISSUE TITLE
Change default choice: "Only if absolutely necessary" looks a bit out of place

### ISSUE THREAD

**Issue by irgendwr** [fsinfuhh/Bitpoll#73]
This may be nitpicky, but I do not like that "Only if absolutely necessary" is capitalized and so long compared to the other choices :smile: 

Current default:
![image](https://user-images.githubusercontent.com/17804578/101301755-1d8d7300-383a-11eb-9268-fd5149709f7b.png)

A) Slightly better:
![image](https://user-images.githubusercontent.com/17804578/101301834-4ada2100-383a-11eb-9209-e14f9b8d271f.png)

B) I can finally exist in peace:
![image](https://user-images.githubusercontent.com/17804578/101301958-a3112300-383a-11eb-88e5-3d1d86737b52.png)

C) same as B but capitalized:
![image](https://user-images.githubusercontent.com/17804578/101302225-4cf0af80-383b-11eb-8d62-2a3b2dced7e9.png)

I guess it depends on personal preference, but it should at least be consistent. Should we vote on this?

**Comment by irgendwr** [comment]
Continuing my unnecessary nitpickyness: maybe other things should also be capitalized 
![image](https://user-images.githubusercontent.com/17804578/101302597-4adb2080-383c-11eb-92e5-595d62b7b1d9.png)

**Comment by Swanand01** [comment]
Hi, I am a first time contributor and I'd like to help.

**Comment by timonegk** [comment]
Hi, thank you for your interest in contributing! Feel free to open a pull request for your changes. Regarding what to change “Only if absolutely necessary” to, I think we settled on “Rather not” in an internal discussion about the topic.
