### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by witchent** [fsinfuhh/Bitpoll#83]
Even while nobody is using my bitpoll instance, the python process (running python ./manage.py runserver 0.0.0.0:8888) uses around 16% of my cpu (measured via top). Admittedly it is not a powerful NCU, but that still seems very high just for idling.
Is there anything I can do to help find the root cause?

**Comment by harryfiedify** [comment]
I encountered the same issue, fixed by running with `./manage.py runserver --noreload`

from https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/184

**Comment by ftsell** [comment]
Generally `./manage.py runserver` is not intended for use in production settings 

See the [django-admin reference](https://docs.djangoproject.com/en/4.0/ref/django-admin/#runserver):
> It has not gone through security audits or performance tests.

**Comment by timonegk** [comment]
Feel free to reopen if the problem persists with a production server (uwsgi, gunicorn, ...).
