### ISSUE TITLE
Reference site: https://bitpoll.mafiasi.de/ is down

### ISSUE THREAD

**Issue by CarliJoy** [fsinfuhh/Bitpoll#96]
The site https://bitpoll.mafiasi.de/ seems to be down:
![image](https://user-images.githubusercontent.com/7687556/126195852-3444740a-b4d9-4bbf-be41-59683c3dacb4.png)

**Comment by timonegk** [comment]
Hi, due to ongoing electricity checks, the server hosting the site will be down until tomorrow afternoon (CEST). Sorry for the inconvenience!

**Comment by CarliJoy** [comment]
Thank you for the information :-)
